package utils;

public enum CenaNome {
    LOGIN,
    HOMEPAGE,
    HOMEPAGE_FUNC, 

    MANTER_ALUGUEL, 
    MANTER_CLIENTE, 
    MANTER_FUNC, 
    MANTER_VESTIDO,
    CADASTRO_CLIENTE,

    BUSCAR_VESTIDO, 
    ALUGAR_VESTIDO, 
    CONSULTAR_ALUGEL, 
    REALIZAR_PAG  
}
